"""Hand-crafted realistic responses keyed by schema name.

Used by `MockLLMProvider` so reviewers without an OpenAI key can still
exercise the full pipeline. Values target the architecture's sample
acceptance: ~30–50% match score, ≥ 8 required gaps, etc.
"""

MOCK_RESPONSES: dict[str, dict] = {
    "ResumeStructured": {
        "years_experience": 4,
        "role": "Frontend Developer",
        "skills": [
            {"name": "HTML", "proficiency": "strong", "evidence": "Built responsive layouts."},
            {"name": "CSS", "proficiency": "strong", "evidence": "Authored maintainable styles."},
            {"name": "JavaScript", "proficiency": "strong", "evidence": "Primary language for 4 years."},
            {"name": "React", "proficiency": "strong", "evidence": "Daily driver for SPA work."},
            {"name": "Git", "proficiency": "used", "evidence": "Standard team workflow."},
            {"name": "REST APIs", "proficiency": "used", "evidence": "Consumed REST endpoints."},
            {"name": "Jest", "proficiency": "used", "evidence": "Unit tests on critical UI."},
            {"name": "Responsive Design", "proficiency": "strong", "evidence": "Mobile-first focus."},
            {"name": "Accessibility", "proficiency": "used", "evidence": "WCAG-aware components."},
            {"name": "Code Review", "proficiency": "used", "evidence": "Reviewed teammate PRs."},
        ],
        "domains": ["frontend", "web"],
    },
    "JdStructured": {
        "role": "Senior Full-Stack Developer",
        "seniority": "senior",
        "required": [
            {"skill": "TypeScript", "weight": 5, "source_quote": "TypeScript, React, Next.js"},
            {"skill": "React", "weight": 4, "source_quote": "TypeScript, React, Next.js"},
            {"skill": "Next.js", "weight": 5, "source_quote": "TypeScript, React, Next.js"},
            {"skill": "Node.js", "weight": 5, "source_quote": "Node.js + Express"},
            {"skill": "Express", "weight": 4, "source_quote": "Node.js + Express"},
            {"skill": "PostgreSQL", "weight": 5, "source_quote": "PostgreSQL, GraphQL"},
            {"skill": "GraphQL", "weight": 5, "source_quote": "PostgreSQL, GraphQL"},
            {"skill": "Docker", "weight": 4, "source_quote": "Docker, CI/CD pipelines"},
            {"skill": "CI/CD", "weight": 4, "source_quote": "Docker, CI/CD pipelines"},
            {"skill": "Integration Testing", "weight": 4, "source_quote": "Integration tests"},
            {"skill": "System Design", "weight": 4, "source_quote": "System design and code review"},
            {"skill": "Code Review", "weight": 3, "source_quote": "System design and code review"},
        ],
        "nice_to_have": [
            {"skill": "Redis", "weight": 2, "source_quote": "Nice to have: Redis"},
            {"skill": "AWS", "weight": 2, "source_quote": "AWS deployments"},
            {"skill": "Observability", "weight": 2, "source_quote": "Observability tooling"},
            {"skill": "LLM APIs", "weight": 2, "source_quote": "LLM APIs"},
        ],
    },
    "GapAnalysis": {
        "overall_match_score": 38,
        "gaps": [
            {
                "skill": "TypeScript",
                "category": "required",
                "severity": 5,
                "status": "missing",
                "evidence": "JD lists TypeScript as required; resume only mentions JavaScript.",
                "jd_quote": "TypeScript, React, Next.js",
                "search_query": "TypeScript tutorial for beginners",
            },
            {
                "skill": "Next.js",
                "category": "required",
                "severity": 5,
                "status": "missing",
                "evidence": "JD requires Next.js; resume has no framework experience.",
                "jd_quote": "TypeScript, React, Next.js",
                "search_query": "Next.js app router tutorial",
            },
            {
                "skill": "Node.js",
                "category": "required",
                "severity": 5,
                "status": "missing",
                "evidence": "JD requires Node.js for backend; resume is frontend-only.",
                "jd_quote": "Node.js + Express",
                "search_query": "Node.js full course",
            },
            {
                "skill": "PostgreSQL",
                "category": "required",
                "severity": 5,
                "status": "missing",
                "evidence": "JD requires PostgreSQL; resume has no database experience.",
                "jd_quote": "PostgreSQL, GraphQL",
                "search_query": "PostgreSQL tutorial",
            },
            {
                "skill": "GraphQL",
                "category": "required",
                "severity": 5,
                "status": "missing",
                "evidence": "JD requires GraphQL; resume only uses REST.",
                "jd_quote": "PostgreSQL, GraphQL",
                "search_query": "GraphQL crash course",
            },
            {
                "skill": "Docker",
                "category": "required",
                "severity": 4,
                "status": "missing",
                "evidence": "JD requires Docker; resume has no devops experience.",
                "jd_quote": "Docker, CI/CD pipelines",
                "search_query": "Docker tutorial for beginners",
            },
            {
                "skill": "CI/CD",
                "category": "required",
                "severity": 4,
                "status": "missing",
                "evidence": "JD requires CI/CD; resume has no automation experience.",
                "jd_quote": "Docker, CI/CD pipelines",
                "search_query": "GitHub Actions CI/CD tutorial",
            },
            {
                "skill": "Integration Testing",
                "category": "required",
                "severity": 4,
                "status": "weak",
                "evidence": "Resume mentions Jest (unit tests) but not integration tests.",
                "jd_quote": "Integration tests",
                "search_query": "integration testing JavaScript",
            },
            {
                "skill": "System Design",
                "category": "required",
                "severity": 4,
                "status": "missing",
                "evidence": "JD expects system design experience; not present in resume.",
                "jd_quote": "System design and code review",
                "search_query": "system design interview course",
            },
            {
                "skill": "Redis",
                "category": "nice_to_have",
                "severity": 2,
                "status": "missing",
                "evidence": "Listed as nice-to-have in JD; absent from resume.",
                "jd_quote": "Nice to have: Redis",
                "search_query": "Redis crash course",
            },
            {
                "skill": "AWS",
                "category": "nice_to_have",
                "severity": 2,
                "status": "missing",
                "evidence": "Listed as nice-to-have; resume has no cloud experience.",
                "jd_quote": "AWS deployments",
                "search_query": "AWS full course",
            },
            {
                "skill": "Observability",
                "category": "nice_to_have",
                "severity": 2,
                "status": "missing",
                "evidence": "Listed as nice-to-have; not present in resume.",
                "jd_quote": "Observability tooling",
                "search_query": "observability tutorial Prometheus Grafana",
            },
            {
                "skill": "LLM APIs",
                "category": "nice_to_have",
                "severity": 2,
                "status": "missing",
                "evidence": "Listed as nice-to-have; not present in resume.",
                "jd_quote": "LLM APIs",
                "search_query": "OpenAI API crash course",
            },
        ],
        "strengths_matching": [
            "React",
            "REST APIs",
            "Jest",
            "Responsive Design",
            "Accessibility",
            "Code Review",
        ],
    },
    "StudyPlan": {
        "items": [
            {
                "gap_skill": "TypeScript",
                "search_queries": ["TypeScript course beginners", "TypeScript with React"],
                "prerequisites": [],
                "estimated_hours": 12,
                "learning_order_rank": 1,
            },
            {
                "gap_skill": "Next.js",
                "search_queries": ["Next.js 14 app router tutorial"],
                "prerequisites": ["TypeScript"],
                "estimated_hours": 16,
                "learning_order_rank": 2,
            },
            {
                "gap_skill": "Node.js",
                "search_queries": ["Node.js full course", "Express tutorial"],
                "prerequisites": [],
                "estimated_hours": 18,
                "learning_order_rank": 3,
            },
            {
                "gap_skill": "PostgreSQL",
                "search_queries": ["PostgreSQL tutorial"],
                "prerequisites": [],
                "estimated_hours": 14,
                "learning_order_rank": 4,
            },
            {
                "gap_skill": "GraphQL",
                "search_queries": ["GraphQL crash course"],
                "prerequisites": ["Node.js"],
                "estimated_hours": 10,
                "learning_order_rank": 5,
            },
            {
                "gap_skill": "Docker",
                "search_queries": ["Docker tutorial beginners"],
                "prerequisites": [],
                "estimated_hours": 8,
                "learning_order_rank": 6,
            },
            {
                "gap_skill": "CI/CD",
                "search_queries": ["GitHub Actions CI/CD tutorial"],
                "prerequisites": ["Docker"],
                "estimated_hours": 6,
                "learning_order_rank": 7,
            },
            {
                "gap_skill": "Integration Testing",
                "search_queries": ["integration testing JavaScript"],
                "prerequisites": [],
                "estimated_hours": 8,
                "learning_order_rank": 8,
            },
            {
                "gap_skill": "System Design",
                "search_queries": ["system design interview"],
                "prerequisites": [],
                "estimated_hours": 24,
                "learning_order_rank": 9,
            },
            {
                "gap_skill": "Redis",
                "search_queries": ["Redis crash course"],
                "prerequisites": [],
                "estimated_hours": 4,
                "learning_order_rank": 10,
            },
            {
                "gap_skill": "AWS",
                "search_queries": ["AWS cloud practitioner"],
                "prerequisites": [],
                "estimated_hours": 20,
                "learning_order_rank": 11,
            },
            {
                "gap_skill": "Observability",
                "search_queries": ["observability Prometheus Grafana"],
                "prerequisites": [],
                "estimated_hours": 6,
                "learning_order_rank": 12,
            },
            {
                "gap_skill": "LLM APIs",
                "search_queries": ["OpenAI API tutorial"],
                "prerequisites": [],
                "estimated_hours": 6,
                "learning_order_rank": 13,
            },
        ],
    },
}
